# https://taskfile.dev

version: '3'

vars:
  GENERATOR_DIR: ./generator
  TEST_OUTPUT_DIR: ./test-output
  PETSTORE_SPEC: ./petstore-tests/petstore.yaml
  TEST_PROJECT: "./petstore-tests/PetstoreApi.Tests/PetstoreApi.Tests.csproj"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ==============================================================================
  # GENERATOR - Build Custom OpenAPI Generator
  # ==============================================================================

  generator:build:
    desc: Build the custom OpenAPI generator JAR
    sources:
      - generator/src/main/java/**/*.java
      - generator/src/main/resources/**/*
      - generator/pom.xml
    generates:
      - generator/target/aspnet-minimalapi-openapi-generator-1.0.0.jar
    cmds:
      - echo "Building custom OpenAPI generator..."
      - |
        cd generator
        mvn clean package -q
      - echo "✓ Generator built successfully"

  generator:download-cli:
    desc: Downloads main generator CLI from Maven
    vars:
      CLI_URL: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.17.0/openapi-generator-cli-7.17.0.jar
    cmds:
      - echo "Downloading OpenAPI Generator CLI..."
      - wget {{.CLI_URL}} -O {{.GENERATOR_DIR}}/openapi-generator-cli.jar
      - echo "✓ Generator CLI downloaded successfully"
    status:
      - test -f "{{.GENERATOR_DIR}}/openapi-generator-cli.jar"

  # ==============================================================================
  # CODEGEN - Generate API Code from OpenAPI Spec
  # ==============================================================================

  gen:petstore:
    desc: Generate server code from OpenAPI spec (with MediatR and optional properties)
    deps:
      - generator:build
      - generator:download-cli
    vars:
      GENERATOR_JAR: "{{.GENERATOR_DIR}}/target/aspnet-minimalapi-openapi-generator-1.0.0.jar"
      CLI_JAR: "{{.GENERATOR_DIR}}/openapi-generator-cli.jar"
      ADDITIONAL_PROPS: '{{.ADDITIONAL_PROPS | default "packageName=PetstoreApi,useMediatr=true,useValidators=true"}}'
    cmds:
      - echo "Deleting old generated code..."
      - rm -rf {{.TEST_OUTPUT_DIR}}
      - echo "Generating server code with properties {{.ADDITIONAL_PROPS}}..."
      - |
        java -cp "{{.GENERATOR_JAR}}:{{.CLI_JAR}}" \
          org.openapitools.codegen.OpenAPIGenerator generate \
          -g aspnetcore-minimalapi \
          -i {{.PETSTORE_SPEC}} \
          -o {{.TEST_OUTPUT_DIR}} \
          --additional-properties {{.ADDITIONAL_PROPS}}
      - echo "✓ Server code generated"

  gen:copy-test-stubs:
    desc: Copy test handlers and test project over generated stubs
    vars:
      TEST_HANDLERS_DIR: ./petstore-tests/TestHandlers
      TEST_EXTENSIONS_DIR: ./petstore-tests/TestExtensions
      TEST_PROJECT_DIR: ./petstore-tests/PetstoreApi.Tests
      OUTPUT_HANDLERS_DIR: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/Handlers"
      OUTPUT_SERVICES_DIR: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/Services"
      OUTPUT_EXTENSIONS_DIR: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/Extensions"
    cmds:
      - echo "Copying test project..."
      - mkdir -p {{.TEST_OUTPUT_DIR}}/tests
      - cp -r {{.TEST_PROJECT_DIR}} {{.TEST_OUTPUT_DIR}}/tests/
      - echo "✓ Test project copied"
      - echo "Copying test handler implementations..."
      - mkdir -p {{.OUTPUT_SERVICES_DIR}}
      - cp {{.TEST_HANDLERS_DIR}}/GetPetByIdQueryHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/AddPetCommandHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/UpdatePetCommandHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/DeletePetCommandHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/FindPetsByStatusQueryHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/FindPetsByTagsQueryHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/InMemoryPetStore.cs {{.OUTPUT_SERVICES_DIR}}/
      - echo "✓ Test handlers copied successfully"
      - echo "Copying ServiceCollectionExtensions with IPetStore registration..."
      - cp {{.TEST_EXTENSIONS_DIR}}/ServiceCollectionExtensions.cs {{.OUTPUT_EXTENSIONS_DIR}}/
      - echo "✓ ServiceCollectionExtensions copied successfully"

  # ==============================================================================
  # BUILD - Compile Generated Code
  # ==============================================================================

  build:all:
    desc: Build entire solution (both projects when NuGet packaging enabled)
    cmds:
      - echo "Building entire solution..."
      - dotnet build {{.TEST_OUTPUT_DIR}}/ --verbosity minimal
      - echo "✓ Solution built successfully"
    preconditions:
      - test -f {{.TEST_OUTPUT_DIR}}/PetstoreApi.sln

  build:contracts-nuget:
    desc: Build the Contracts project only (for NuGet packaging workflow)
    cmds:
      - echo "Building Contracts project..."
      - dotnet build {{.TEST_OUTPUT_DIR}}/src/PetstoreApi.Contracts/ --verbosity minimal
      - echo "✓ Contracts built successfully"
    preconditions:
      - test -f {{.TEST_OUTPUT_DIR}}/src/PetstoreApi.Contracts/PetstoreApi.Contracts.csproj

  build:impl-nuget:
    desc: Build Implementation project that uses Contracts via NuGet package reference
    deps:
      - build:contracts-nuget
    cmds:
      - echo "Building Implementation project (using NuGet contracts)..."
      - dotnet build {{.TEST_OUTPUT_DIR}}/src/PetstoreApi/ --verbosity minimal
      - echo "✓ Implementation built successfully (with NuGet contracts)"
    preconditions:
      - test -f {{.TEST_OUTPUT_DIR}}/src/PetstoreApi/PetstoreApi.csproj

  # ==============================================================================
  # TEST - Unit & Integration Testing
  # ==============================================================================

  test:generator:
    desc: Run generator unit tests (validates mustache templates directly - no code generation required)
    cmds:
      - |
        if ls generator-tests/*.csproj 1> /dev/null 2>&1; then
          echo "Running generator unit tests (template validation)..."
          dotnet test generator-tests/ --verbosity normal
        else
          echo "⚠️  Generator tests not yet implemented"
          echo "   Directory: generator-tests/ exists but no .csproj found"
          echo "   To set up: cd generator-tests && dotnet new xunit --name GeneratorTests"
        fi

  test:petstore-unit:
    desc: Run xUnit tests for generated petstore API (assumes code already generated)
    deps:
      - gen:copy-test-stubs
    cmds:
      - echo "Running petstore unit tests..."
      - dotnet test {{.TEST_PROJECT}} --verbosity normal

  test:petstore-integration:
    desc: Full petstore API lifecycle test (start → wait → Bruno tests → stop)
    vars:
      SUITE: '{{.SUITE | default ""}}'
    deps:
      - gen:copy-test-stubs
    cmds:
      - task: api:start
      - defer: { task: api:stop }
      - task: api:wait
      - task: bruno:run{{if .SUITE}}-{{.SUITE}}{{end}}

  test:petstore-integration-single:
    desc: Run specific petstore Bruno test(s) with full lifecycle (usage - task test:petstore-integration-single TEST='pet/add-pet.bru')
    vars:
      TEST: '{{.TEST | default "pet/Add a new pet to the store.bru"}}'
    deps:
      - gen:copy-test-stubs
    cmds:
      - task: api:start
      - defer: { task: api:stop }
      - task: api:wait
      - task: bruno:run-single
        vars: {TEST: '{{.TEST}}'}

  # ==============================================================================
  # Regression Tests - Full tests including generation with different options
  # ==============================================================================


  regress:full-petstore-validators-problemdetails:
    desc: "Full petstore regression (build + generate + test)"
    cmds:
      - task: clean:all
      - task: build-generator
      - task: gen:petstore 
        vars: {ADDITIONAL_PROPS: "packageName=PetstoreApi,useMediatr=true,useValidators=true,useProblemDetails=true"}
      - task: test:petstore-unit
      - task: test:petstore-integration
      - task: test:generator
 


  # ==============================================================================
  # API - Manage Test API Server
  # ==============================================================================

  api:run:
    desc: Launch the generated Petstore API server (foreground)
    vars:
      API_PROJECT: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/PetstoreApi.csproj"
    deps:
      - gen:copy-test-stubs
    cmds:
      - echo "Starting Petstore API server..."
      - dotnet run --project {{.API_PROJECT}}

  api:start:
    desc: Start the .NET API in background and save PID
    deps:
      - gen:copy-test-stubs
    dir: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi"
    cmds:
      - bash -c 'nohup dotnet run > /dev/null 2>&1 & echo $! > ../.server.pid'
      - echo "API starting with PID $(cat ../.server.pid)..."

  api:wait:
    desc: Wait until the API is healthy
    cmds:
      - echo "Waiting for API to be healthy..."
      - |
        until curl --output /dev/null --silent --head --fail -X GET http://localhost:5198/health; do
          printf '.'
          sleep 1
        done
      - echo "\nAPI is up!"

  api:stop:
    desc: Stop the background API using saved PID
    dir: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi"
    cmds:
      - |
        if [ -f ../.server.pid ]; then
          PID=$(cat ../.server.pid)
          echo "Stopping API (PID $PID)..."
          bash -c "kill $PID" || true
          rm ../.server.pid
        else
          echo "No PID file found. Kill any process on port 5198 as fallback..."
          lsof -ti:5198 | xargs kill -9 || true
        fi

  # ==============================================================================
  # BRUNO - API Test Suites
  # ==============================================================================

  bruno:run:
    desc: Run all Bruno API tests
    dir: ./bruno/OpenAPI_Petstore
    cmds:
      - echo "Running Bruno tests..."
      - bru run --env Local

  bruno:run-main-suite:
    desc: Run main pet test suite (6 tests - CRUD operations)
    dir: ./bruno/OpenAPI_Petstore
    cmds:
      - bru run pet/main-pet-test-suite --env Local

  bruno:run-validation-suite:
    desc: Run validation test suite (13 tests - FluentValidation)
    dir: ./bruno/OpenAPI_Petstore
    cmds:
      - bru run pet/validation-pet-test-suite --env Local

  bruno:run-all-suites:
    desc: Run both main + validation suites (19 tests total)
    cmds:
      - task: bruno:run-main-suite
      - task: bruno:run-validation-suite

  bruno:run-single:
    desc: Run one or more Bruno test files
    vars:
      BRUNO_DIR: ./bruno/OpenAPI_Petstore
      TEST: '{{.TEST | default "pet/Add a new pet to the store.bru"}}'
    dir: '{{.BRUNO_DIR}}'
    cmds:
      - echo "Running Bruno test(s) - {{.TEST}}"
      - bru run --env Local {{.TEST}}

  # ==============================================================================
  # DOCKER - Container Management
  # ==============================================================================

  docker:build:
    desc: Build Docker image with custom OpenAPI generator
    vars:
      IMAGE_NAME: adamsdavis/minimal-api-generator
      IMAGE_TAG: latest
      OPENAPI_GENERATOR_VERSION: 7.10.0
    deps:
      - generator:build
    cmds:
      - echo "Building Docker image..."
      - |
        podman build \
          --build-arg ARG_OPENAPI_GENERATOR_VERSION={{.OPENAPI_GENERATOR_VERSION}} \
          -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          -f docker/Dockerfile \
          .
      - echo "✓ Docker image built - {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  docker:push:
    desc: Push Docker image to registry
    vars:
      IMAGE_NAME: adamsdavis/minimal-api-generator
      IMAGE_TAG: latest
    cmds:
      - echo "Pushing Docker image to registry..."
      - podman push {{.IMAGE_NAME}}:{{.IMAGE_TAG}}
      - echo "✓ Image pushed - {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  docker:test:
    desc: Test Docker image by generating code
    vars:
      IMAGE_NAME: adamsdavis/minimal-api-generator
      IMAGE_TAG: latest
      DOCKER_TEST_OUTPUT: ./docker-test-output
    cmds:
      - echo "Testing Docker image..."
      - rm -rf {{.DOCKER_TEST_OUTPUT}}
      - mkdir -p {{.DOCKER_TEST_OUTPUT}}
      - |
        docker run --rm \
          -v $(pwd):/workspace \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          generate \
          -g aspnetcore-minimalapi \
          -i /workspace/petstore-tests/petstore.yaml \
          -o /workspace/{{.DOCKER_TEST_OUTPUT}} \
          --additional-properties packageName=PetstoreApi,useMediatr=true
      - echo "✓ Docker test complete. Output in {{.DOCKER_TEST_OUTPUT}}"
      - test -f {{.DOCKER_TEST_OUTPUT}}/src/PetstoreApi/Program.cs || (echo "❌ Program.cs NOT found" && exit 1)
      - test -f {{.DOCKER_TEST_OUTPUT}}/src/PetstoreApi/Commands/AddPetCommand.cs || (echo "❌ MediatR Commands NOT found" && exit 1)
      - echo "✅ All validation checks passed"

  # ==============================================================================
  # CLEAN - Cleanup Tasks
  # ==============================================================================

  clean:generated:
    desc: Clean only generated Minimal API code (keeps generator artifacts)
    cmds:
      - echo "Cleaning generated Minimal API code..."
      - rm -rf {{.TEST_OUTPUT_DIR}}
      - echo "✓ Generated API code cleaned"

  clean:all:
    desc: Clean all generated code and build artifacts
    cmds:
      - echo "Cleaning all generated code..."
      - rm -rf {{.TEST_OUTPUT_DIR}}
      - echo "Cleaning generator build artifacts..."
      - |
        cd generator
        mvn clean
      - echo "✓ Cleaned"

  # ==============================================================================
  # LEGACY ALIASES - Deprecated, use namespaced versions above
  # ==============================================================================

  build-generator:
    desc: "[DEPRECATED] Use generator:build"
    cmds:
      - task: generator:build

  generate-petstore-minimal-api:
    desc: "[DEPRECATED] Use gen:petstore"
    cmds:
      - task: gen:petstore
        vars:
          ADDITIONAL_PROPS: '{{.ADDITIONAL_PROPS}}'

  copy-test-stubs:
    desc: "[DEPRECATED] Use gen:copy-test-stubs"
    cmds:
      - task: gen:copy-test-stubs

  quick-test:
    desc: "[DEPRECATED] Use test:petstore-unit"
    cmds:
      - task: test:petstore-unit

  test-ci:
    desc: "[DEPRECATED] Use test:petstore-integration"
    cmds:
      - task: test:petstore-integration

  run-petstore-api:
    desc: "[DEPRECATED] Use api:run"
    cmds:
      - task: api:run

  clean-generated-api:
    desc: "[DEPRECATED] Use clean:generated"
    cmds:
      - task: clean:generated

