# https://taskfile.dev

version: '3'

vars:
  GENERATOR_DIR: ./generator
  TEST_OUTPUT_DIR: ./test-output
  PETSTORE_SPEC: ./petstore-tests/petstore.yaml
  TEST_PROJECT: "{{.TEST_OUTPUT_DIR}}/tests/PetstoreApi.Tests/PetstoreApi.Tests.csproj"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build-generator:
    desc: Build the custom OpenAPI generator JAR
    sources:
      - generator/src/main/java/**/*.java
      - generator/src/main/resources/**/*
      - generator/pom.xml
    generates:
      - generator/target/aspnet-minimalapi-openapi-generator-1.0.0.jar
    cmds:
      - echo "Building custom OpenAPI generator..."
      - |
        cd generator
        mvn clean package -q
      - echo "✓ Generator built successfully"

  get-generator-cli:
    desc: Downloads main generator CLI from Maven
    vars:
      CLI_URL: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.17.0/openapi-generator-cli-7.17.0.jar
    cmds:
      - echo "Downloading OpenAPI Generator CLI..."
      - wget {{.CLI_URL}} -O {{.GENERATOR_DIR}}/openapi-generator-cli.jar
      - echo "✓ Generator CLI downloaded successfully"
    status:
      - test -f "{{.GENERATOR_DIR}}/openapi-generator-cli.jar"

  generate-petstore-minimal-api:
    desc: Generate server code from OpenAPI spec (with MediatR and optional properties)
    deps:
      - build-generator
      - get-generator-cli
    vars:
      GENERATOR_JAR: "{{.GENERATOR_DIR}}/target/aspnet-minimalapi-openapi-generator-1.0.0.jar"
      CLI_JAR: "{{.GENERATOR_DIR}}/openapi-generator-cli.jar"
      ADDITIONAL_PROPS: '{{.ADDITIONAL_PROPS | default "packageName=PetstoreApi,useMediatr=true,useValidators=true"}}'
    cmds:
      - echo "Deleting old generated code..."
      - rm -rf {{.TEST_OUTPUT_DIR}}
      - echo "Generating server code with properties {{.ADDITIONAL_PROPS}}..."
      - |
        java -cp "{{.GENERATOR_JAR}}:{{.CLI_JAR}}" \
          org.openapitools.codegen.OpenAPIGenerator generate \
          -g aspnetcore-minimalapi \
          -i {{.PETSTORE_SPEC}} \
          -o {{.TEST_OUTPUT_DIR}} \
          --additional-properties {{.ADDITIONAL_PROPS}}
      - echo "✓ Server code generated"

  copy-test-stubs:
    desc: Copy test handlers and test project over generated stubs
    vars:
      TEST_HANDLERS_DIR: ./petstore-tests/TestHandlers
      TEST_EXTENSIONS_DIR: ./petstore-tests/TestExtensions
      TEST_PROJECT_DIR: ./petstore-tests/PetstoreApi.Tests
      OUTPUT_HANDLERS_DIR: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/Handlers"
      OUTPUT_SERVICES_DIR: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/Services"
      OUTPUT_EXTENSIONS_DIR: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/Extensions"
    cmds:
      - echo "Copying test project..."
      - mkdir -p {{.TEST_OUTPUT_DIR}}/tests
      - cp -r {{.TEST_PROJECT_DIR}} {{.TEST_OUTPUT_DIR}}/tests/
      - echo "✓ Test project copied"
      - echo "Copying test handler implementations..."
      - mkdir -p {{.OUTPUT_SERVICES_DIR}}
      - cp {{.TEST_HANDLERS_DIR}}/GetPetByIdQueryHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/AddPetCommandHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/UpdatePetCommandHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/DeletePetCommandHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/FindPetsByStatusQueryHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/FindPetsByTagsQueryHandler.cs {{.OUTPUT_HANDLERS_DIR}}/
      - cp {{.TEST_HANDLERS_DIR}}/InMemoryPetStore.cs {{.OUTPUT_SERVICES_DIR}}/
      - echo "✓ Test handlers copied successfully"
      - echo "Copying ServiceCollectionExtensions with IPetStore registration..."
      - cp {{.TEST_EXTENSIONS_DIR}}/ServiceCollectionExtensions.cs {{.OUTPUT_EXTENSIONS_DIR}}/
      - echo "✓ ServiceCollectionExtensions copied successfully"

  test-server-stubs:
    desc: Run tests on generated server with test handlers
    deps:
      - copy-test-stubs
    cmds:
      - echo "Running tests..."
      - dotnet test {{.TEST_PROJECT}} --verbosity normal

  run-petstore-api:
    desc: Launch the generated Petstore API server
    vars:
      API_PROJECT: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi/PetstoreApi.csproj"
    deps:
      - copy-test-stubs
    cmds:
      - echo "Starting Petstore API server..."
      - dotnet run --project {{.API_PROJECT}}


  # Convenience tasks

  regenerate:
    desc: Complete regeneration workflow (force build + generate + copy stubs + test)
    vars:
      ADDITIONAL_PROPS: '{{.ADDITIONAL_PROPS | default "packageName=PetstoreApi,useMediatr=true,useValidators=true"}}'
    cmds:
      - rm -f generator/target/*.jar
      - task: build-generator
      - task: generate-petstore-minimal-api
        vars:
          ADDITIONAL_PROPS: "{{.ADDITIONAL_PROPS}}"
      - task: test-server-stubs

  quick-test:
    desc: Quick test run (assumes code already generated)
    cmds:
      - task: copy-test-stubs
      - echo "Running tests..."
      - dotnet test {{.TEST_PROJECT}} --verbosity normal

  clean-generated-api:
    desc: Clean only generated Minimal API code (keeps test files)
    cmds:
      - echo "Cleaning generated Minimal API code..."
      - rm -rf {{.TEST_OUTPUT_DIR}}
      - echo "✓ Generated API code cleaned"

  clean-all:
    desc: Clean all generated code and build artifacts
    cmds:
      - echo "Cleaning all generated code..."
      - rm -rf {{.TEST_OUTPUT_DIR}}
      - echo "Cleaning generator build artifacts..."
      - |
        cd generator
        mvn clean
      - echo "✓ Cleaned"

  # Docker tasks

  docker-build:
    desc: Build Docker image with custom OpenAPI generator
    vars:
      IMAGE_NAME: adamsdavis/minimal-api-generator
      IMAGE_TAG: latest
      OPENAPI_GENERATOR_VERSION: 7.10.0
    deps:
      - build-generator
    cmds:
      - echo "Building Docker image..."
      - |
        podman build \
          --build-arg ARG_OPENAPI_GENERATOR_VERSION={{.OPENAPI_GENERATOR_VERSION}} \
          -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          -f docker/Dockerfile \
          .
      - echo "✓ Docker image built - {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  docker-push:
    desc: Push Docker image to registry
    vars:
      IMAGE_NAME: adamsdavis/minimal-api-generator
      IMAGE_TAG: latest
    cmds:
      - echo "Pushing Docker image to registry..."
      - podman push {{.IMAGE_NAME}}:{{.IMAGE_TAG}}
      - echo "✓ Image pushed - {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  docker-test:
    desc: Test Docker image by generating code
    vars:
      IMAGE_NAME: adamsdavis/minimal-api-generator
      IMAGE_TAG: latest
      DOCKER_TEST_OUTPUT: ./docker-test-output
    cmds:
      - echo "Testing Docker image..."
      - rm -rf {{.DOCKER_TEST_OUTPUT}}
      - mkdir -p {{.DOCKER_TEST_OUTPUT}}
      - |
        docker run --rm \
          -v $(pwd):/workspace \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          generate \
          -g aspnetcore-minimalapi \
          -i /workspace/petstore-tests/petstore.yaml \
          -o /workspace/{{.DOCKER_TEST_OUTPUT}} \
          --additional-properties packageName=PetstoreApi,useMediatr=true
      - echo "✓ Docker test complete. Output in {{.DOCKER_TEST_OUTPUT}}"
      - test -f {{.DOCKER_TEST_OUTPUT}}/src/PetstoreApi/Program.cs || (echo "❌ Program.cs NOT found" && exit 1)
      - test -f {{.DOCKER_TEST_OUTPUT}}/src/PetstoreApi/Commands/AddPetCommand.cs || (echo "❌ MediatR Commands NOT found" && exit 1)
      - echo "✅ All validation checks passed"


  # 1. Orchestration Task
  # This runs the full lifecycle: Start -> Wait -> Test -> Stop
  test-ci:
    desc: "Modern approach using defer for cleanup"
    cmds:
      - task: api:start
      - defer: { task: api:stop } # This runs when test-ci finishes, success or fail
      - task: api:wait
      - task: bruno:run

  single-bruno-test:
    desc: "Run one or more Bruno tests with full lifecycle (usage: task single-bruno-test TEST='pet/add-pet.bru pet/delete-pet.bru')"
    vars:
      TEST: '{{.TEST | default "pet/Add a new pet to the store.bru"}}'
    cmds:
      - task: api:start
      - defer: { task: api:stop }
      - task: api:wait
      - task: bruno:run-single
        vars: {TEST: '{{.TEST}}'}


  # 2. Start API in Background
  api:start:
    desc: "Starts the .NET API in the background and saves the PID."
    deps:
      - copy-test-stubs
    dir: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi"
    cmds:
      # 'nohup' prevents the process from dying if the shell closes.
      # '> /dev/null 2>&1' silences output (optional, remove to see logs).
      # '&' runs it in the background.
      # 'echo $! > .server.pid' saves the Process ID to a file.
      - bash -c 'nohup dotnet run > /dev/null 2>&1 & echo $! > ../.server.pid'
      - echo "API starting with PID $(cat ../.server.pid)..."

  # 3. Wait for Health Check
  api:wait:
    desc: "Waits until the API is available on the port."
    cmds:
      - echo "Waiting for API to be healthy..."
      # Loops until localhost:5198 gives a 200 OK. Adjust port/path as needed.
      - |
        until curl --output /dev/null --silent --head --fail -X GET http://localhost:5198/health; do
          printf '.'
          sleep 1
        done
      - echo "\nAPI is up!"

  # 4. Run Bruno Tests
  bruno:run:
    desc: "Runs Bruno API tests."
    dir: ./bruno/OpenAPI_Petstore
    cmds:
      - echo "Running Bruno tests..."
      # Assumes your .bru files are in a 'tests' folder
      - bru run --env Local

  bruno:run-single:
    desc: "Runs one or more Bruno test files."
    vars:
      BRUNO_DIR: ./bruno/OpenAPI_Petstore
      TEST: '{{.TEST | default "pet/Add a new pet to the store.bru"}}'
    dir: '{{.BRUNO_DIR}}'
    cmds:
      - echo "Running Bruno test(s) - {{.TEST}}"
      - bru run --env Local {{.TEST}}

  # 5. Shutdown Server
  api:stop:
    desc: "Stops the background API using the saved PID."
    dir: "{{.TEST_OUTPUT_DIR}}/src/PetstoreApi"
    cmds:
      # Check if PID file exists, read it, kill process, remove file.
      - |
        if [ -f ../.server.pid ]; then
          PID=$(cat ../.server.pid)
          echo "Stopping API (PID $PID)..."
          kill -9 $PID || true
          rm ../.server.pid
        else
          echo "No PID file found. Kill any process on port 5198 as fallback..."
          lsof -ti:5198 | xargs kill -9 || true
        fi