// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.Models;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for FindPetsByStatus operation
/// 
/// Finds Pets by status
/// 
/// </summary>
public record FindPetsByStatusQuery : IRequest<List<Pet>>
{
    /// <summary>
    /// Status values that need to be considered for filter
    /// </summary>
    public List<string> status { get; init; }

}
