// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.Models;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for GetOrderById operation
/// 
/// Find purchase order by ID
/// 
/// </summary>
public record GetOrderByIdQuery : IRequest<Order>
{
    /// <summary>
    /// ID of pet that needs to be fetched
    /// </summary>
    public long orderId { get; init; }

}
