// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for AddPetCommand
/// </summary>
public class AddPetCommandHandler : IRequestHandler<AddPetCommand, Pet>
{
    private readonly IPetStore _petStore;

    public AddPetCommandHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the AddPetCommand request
    /// </summary>
    public async Task<Pet> Handle(AddPetCommand request, CancellationToken cancellationToken)
    {
        var pet = _petStore.Add(request.pet);
        return await Task.FromResult(pet);
    }
}
