// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for AddPetCommand
/// </summary>
public class AddPetCommandHandler : IRequestHandler<AddPetCommand, Pet>
{
    // TODO: Add dependencies via constructor injection
    // Example:
    // private readonly ILogger<AddPetCommandHandler> _logger;
    // private readonly ApplicationDbContext _db;
    //
    // public AddPetCommandHandler(
    //     ILogger<AddPetCommandHandler> logger,
    //     ApplicationDbContext db)
    // {
    //     _logger = logger;
    //     _db = db;
    // }

    /// <summary>
    /// Handles the AddPetCommand request
    /// </summary>
    public async Task<Pet> Handle(AddPetCommand request, CancellationToken cancellationToken)
    {
        // TODO: Implement AddPet logic
        throw new NotImplementedException("Handler for AddPet not yet implemented");
    }
}
