// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for GetUserByNameQuery
/// </summary>
public class GetUserByNameQueryHandler : IRequestHandler<GetUserByNameQuery, User>
{
    // TODO: Add dependencies via constructor injection
    // Example:
    // private readonly ILogger<GetUserByNameQueryHandler> _logger;
    // private readonly ApplicationDbContext _db;
    //
    // public GetUserByNameQueryHandler(
    //     ILogger<GetUserByNameQueryHandler> logger,
    //     ApplicationDbContext db)
    // {
    //     _logger = logger;
    //     _db = db;
    // }

    /// <summary>
    /// Handles the GetUserByNameQuery request
    /// </summary>
    public async Task<User> Handle(GetUserByNameQuery request, CancellationToken cancellationToken)
    {
        // TODO: Implement GetUserByName logic
        throw new NotImplementedException("Handler for GetUserByName not yet implemented");
    }
}
