// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for UpdatePetCommand
/// </summary>
public class UpdatePetCommandHandler : IRequestHandler<UpdatePetCommand, Pet>
{
    private readonly IPetStore _petStore;

    public UpdatePetCommandHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the UpdatePetCommand request
    /// </summary>
    public async Task<Pet> Handle(UpdatePetCommand request, CancellationToken cancellationToken)
    {
        var pet = _petStore.Update(request.pet);
        return await Task.FromResult(pet);
    }
}
