// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for AddPetCommand
/// </summary>
public class AddPetCommandHandler : IRequestHandler<AddPetCommand, PetDto>
{
    private readonly IPetStore _petStore;

    public AddPetCommandHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the AddPetCommand request
    /// </summary>
    public async Task<PetDto> Handle(AddPetCommand request, CancellationToken cancellationToken)
    {
        // DEBUG: Log incoming values
        Console.WriteLine($"[AddPetHandler] Received ID: {request.pet.Id?.ToString() ?? "NULL"}");
        Console.WriteLine($"[AddPetHandler] Received Status: {request.pet.Status}");
        Console.WriteLine($"[AddPetHandler] Received Name: {request.pet.Name ?? "NULL"}");
        
        // Map DTO to Model
        var pet = new Pet
        {
            Id = request.pet.Id ?? 0, // Use provided ID, or 0 to auto-generate
            Category = request.pet.Category != null ? new Category { Id = request.pet.Category.Id.GetValueOrDefault(), Name = request.pet.Category.Name } : null,
            Name = request.pet.Name,
            PhotoUrls = request.pet.PhotoUrls,
            Tags = request.pet.Tags?.Select(t => new Tag { Id = t.Id.GetValueOrDefault(), Name = t.Name }).ToList(),
            Status = MapDtoStatusToModelStatus(request.pet.Status)
        };
        
        Console.WriteLine($"[AddPetHandler] Mapped to Pet.Id: {pet.Id}, Pet.Status: {pet.Status}");
        
        var result = _petStore.Add(pet);
        
        Console.WriteLine($"[AddPetHandler] After Add - Pet.Id: {result.Id}, Pet.Status: {result.Status}");
        
        // Map Model back to DTO for response
        var resultDto = MapPetToDto(result);
        
        return await Task.FromResult(resultDto);
    }

    private static Pet.StatusEnum MapDtoStatusToModelStatus(AddPetDto.StatusEnum? status)
    {
        if (!status.HasValue) return Pet.StatusEnum.AvailableEnum;
        
        return status.Value switch
        {
            AddPetDto.StatusEnum.AvailableEnum => Pet.StatusEnum.AvailableEnum,
            AddPetDto.StatusEnum.PendingEnum => Pet.StatusEnum.PendingEnum,
            AddPetDto.StatusEnum.SoldEnum => Pet.StatusEnum.SoldEnum,
            _ => Pet.StatusEnum.AvailableEnum
        };
    }

    private static PetDto MapPetToDto(Pet pet)
    {
        return new PetDto
        {
            Id = pet.Id,
            Category = pet.Category != null ? new CategoryDto { Id = pet.Category.Id, Name = pet.Category.Name } : null,
            Name = pet.Name,
            PhotoUrls = pet.PhotoUrls,
            Tags = pet.Tags?.Select(t => new TagDto { Id = t.Id, Name = t.Name }).ToList(),
            Status = MapModelStatusToDtoStatus(pet.Status)
        };
    }

    private static PetDto.StatusEnum MapModelStatusToDtoStatus(Pet.StatusEnum status)
    {
        return status switch
        {
            Pet.StatusEnum.AvailableEnum => PetDto.StatusEnum.AvailableEnum,
            Pet.StatusEnum.PendingEnum => PetDto.StatusEnum.PendingEnum,
            Pet.StatusEnum.SoldEnum => PetDto.StatusEnum.SoldEnum,
            _ => PetDto.StatusEnum.AvailableEnum
        };
    }
}
