// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for FindPetsByStatusQuery
/// </summary>
public class FindPetsByStatusQueryHandler : IRequestHandler<FindPetsByStatusQuery, List<Pet>>
{
    private readonly IPetStore _petStore;

    public FindPetsByStatusQueryHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the FindPetsByStatusQuery request
    /// </summary>
    public async Task<List<Pet>> Handle(FindPetsByStatusQuery request, CancellationToken cancellationToken)
    {
        // DEBUG: Log what we received
        Console.WriteLine($"[FindByStatusHandler] Received status array: {request.status?.Length ?? 0} items");
        if (request.status != null)
        {
            foreach (var s in request.status)
            {
                Console.WriteLine($"[FindByStatusHandler] Status item: '{s}'");
            }
        }
        
        var pets = _petStore.FindByStatus(request.status);
        
        Console.WriteLine($"[FindByStatusHandler] Found {pets.Count()} pets");
        
        return await Task.FromResult(pets.ToList());
    }
}
