// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for FindPetsByTagsQuery
/// </summary>
public class FindPetsByTagsQueryHandler : IRequestHandler<FindPetsByTagsQuery, List<Pet>>
{
    private readonly IPetStore _petStore;

    public FindPetsByTagsQueryHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the FindPetsByTagsQuery request
    /// </summary>
    public async Task<List<Pet>> Handle(FindPetsByTagsQuery request, CancellationToken cancellationToken)
    {
        var pets = _petStore.FindByTags(request.tags);
        return await Task.FromResult(pets.ToList());
    }
}
