// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for GetPetByIdQuery
/// </summary>
public class GetPetByIdQueryHandler : IRequestHandler<GetPetByIdQuery, PetDto>
{
    private readonly IPetStore _petStore;

    public GetPetByIdQueryHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the GetPetByIdQuery request
    /// </summary>
    public async Task<PetDto> Handle(GetPetByIdQuery request, CancellationToken cancellationToken)
    {
        var pet = _petStore.GetById(request.petId);
        
        // Return null if pet not found (will result in 404)
        if (pet == null)
        {
            return null;
        }
        
        // Map Model to DTO for response
        var petDto = MapPetToDto(pet);
        
        return await Task.FromResult(petDto);
    }

    private static PetDto MapPetToDto(Pet pet)
    {
        return new PetDto
        {
            Id = pet.Id,
            Category = pet.Category != null ? new CategoryDto { Id = pet.Category.Id, Name = pet.Category.Name } : null,
            Name = pet.Name,
            PhotoUrls = pet.PhotoUrls,
            Tags = pet.Tags?.Select(t => new TagDto { Id = t.Id, Name = t.Name }).ToList(),
            Status = MapModelStatusToDtoStatus(pet.Status)
        };
    }

    private static PetDto.StatusEnum MapModelStatusToDtoStatus(Pet.StatusEnum status)
    {
        return status switch
        {
            Pet.StatusEnum.AvailableEnum => PetDto.StatusEnum.AvailableEnum,
            Pet.StatusEnum.PendingEnum => PetDto.StatusEnum.PendingEnum,
            Pet.StatusEnum.SoldEnum => PetDto.StatusEnum.SoldEnum,
            _ => PetDto.StatusEnum.AvailableEnum
        };
    }
}
