// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for UpdatePetCommand
/// </summary>
public class UpdatePetCommandHandler : IRequestHandler<UpdatePetCommand, PetDto>
{
    private readonly IPetStore _petStore;

    public UpdatePetCommandHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the UpdatePetCommand request
    /// </summary>
    public async Task<PetDto> Handle(UpdatePetCommand request, CancellationToken cancellationToken)
    {
        // Map DTO to Model
        var pet = new Pet
        {
            Id = request.pet.Id.GetValueOrDefault(),
            Category = request.pet.Category != null ? new Category { Id = request.pet.Category.Id.GetValueOrDefault(), Name = request.pet.Category.Name } : null,
            Name = request.pet.Name,
            PhotoUrls = request.pet.PhotoUrls,
            Tags = request.pet.Tags?.Select(t => new Tag { Id = t.Id.GetValueOrDefault(), Name = t.Name }).ToList(),
            Status = MapDtoStatusToModelStatus(request.pet.Status)
        };
        var result = _petStore.Update(pet);
        
        // Return null if update failed (will result in 404)
        if (result == null)
        {
            return null;
        }
        
        // Map Model back to DTO for response
        var resultDto = MapPetToDto(result);
        
        return await Task.FromResult(resultDto);
    }

    private static Pet.StatusEnum MapDtoStatusToModelStatus(UpdatePetDto.StatusEnum? status)
    {
        if (!status.HasValue) return Pet.StatusEnum.AvailableEnum;
        
        return status.Value switch
        {
            UpdatePetDto.StatusEnum.AvailableEnum => Pet.StatusEnum.AvailableEnum,
            UpdatePetDto.StatusEnum.PendingEnum => Pet.StatusEnum.PendingEnum,
            UpdatePetDto.StatusEnum.SoldEnum => Pet.StatusEnum.SoldEnum,
            _ => Pet.StatusEnum.AvailableEnum
        };
    }

    private static PetDto MapPetToDto(Pet pet)
    {
        return new PetDto
        {
            Id = pet.Id,
            Category = pet.Category != null ? new CategoryDto { Id = pet.Category.Id, Name = pet.Category.Name } : null,
            Name = pet.Name,
            PhotoUrls = pet.PhotoUrls,
            Tags = pet.Tags?.Select(t => new TagDto { Id = t.Id, Name = t.Name }).ToList(),
            Status = MapModelStatusToDtoStatus(pet.Status)
        };
    }

    private static PetDto.StatusEnum MapModelStatusToDtoStatus(Pet.StatusEnum status)
    {
        return status switch
        {
            Pet.StatusEnum.AvailableEnum => PetDto.StatusEnum.AvailableEnum,
            Pet.StatusEnum.PendingEnum => PetDto.StatusEnum.PendingEnum,
            Pet.StatusEnum.SoldEnum => PetDto.StatusEnum.SoldEnum,
            _ => PetDto.StatusEnum.AvailableEnum
        };
    }
}
