// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.Models;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for CreateUser operation
/// 
/// Create user
/// 
/// </summary>
public record CreateUserCommand : IRequest<Unit>
{
    /// <summary>
    /// Created user object
    /// </summary>
    public User user { get; init; }

}
