// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.Models;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for CreateUsersWithListInput operation
/// 
/// Creates list of users with given input array
/// 
/// </summary>
public record CreateUsersWithListInputCommand : IRequest<Unit>
{
    /// <summary>
    /// List of user object
    /// </summary>
    public List<User> user { get; init; }

}
