// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for DeletePetCommand
/// </summary>
public class DeletePetCommandHandler : IRequestHandler<DeletePetCommand, bool>
{
    private readonly IPetStore _petStore;

    public DeletePetCommandHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the DeletePetCommand request
    /// </summary>
    public async Task<bool> Handle(DeletePetCommand request, CancellationToken cancellationToken)
    {
        // Check if pet exists before deletion
        var pet = _petStore.GetById(request.petId);
        if (pet == null)
        {
            return await Task.FromResult(false); // Not found
        }

        _petStore.Delete(request.petId);
        return await Task.FromResult(true); // Success
    }
}
