// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
// Implement your business logic in the Handle method below.
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.Services;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for GetPetByIdQuery
/// </summary>
public class GetPetByIdQueryHandler : IRequestHandler<GetPetByIdQuery, Pet>
{
    private readonly IPetStore _petStore;

    public GetPetByIdQueryHandler(IPetStore petStore)
    {
        _petStore = petStore;
    }

    /// <summary>
    /// Handles the GetPetByIdQuery request
    /// </summary>
    public async Task<Pet> Handle(GetPetByIdQuery request, CancellationToken cancellationToken)
    {
        var pet = _petStore.GetById(request.petId);
        return await Task.FromResult(pet);
    }
}
